spring:
  application:
    name: schgateway
  cloud:
    gateway:
      routes:
        - id: schedulerAdmin
          uri: lb://schedulerAdmin
          predicates:
            - Path=/schedulerAdmin/**
          filters:
            - StripPrefix=1
            - AddRequestHeader=X-Gateway, SpringCloud
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8085/eureka
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
    org.springframework.web.reactive.function.client.ExchangeFunctions: DEBUG
    org.springframework.http.server.reactive: TRACE
    org.springframework.web.reactive: TRACE
    org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: TRACE
security:
  jwt:
    secret-key: YuizCKebQrK8OXhBTEeKOAaTQFY1xIeNtlDfygjA/Ko=
    expiration-time: 3600000
    refresh:
      expiration-time: 3600000